# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='node.proto',
  package='node',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nnode.proto\x12\x04node\x1a\x1bgoogle/protobuf/empty.proto\"m\n\x07Message\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0b\n\x03ttl\x18\x02 \x01(\x05\x12\x0c\n\x04hash\x18\x03 \x01(\x03\x12\x0b\n\x03\x63md\x18\x04 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x05 \x03(\t\x12\x12\n\x05round\x18\x06 \x01(\x05H\x00\x88\x01\x01\x42\x08\n\x06_round\"_\n\x07Weights\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\r\n\x05round\x18\x02 \x01(\x05\x12\x0f\n\x07weights\x18\x03 \x01(\x0c\x12\x14\n\x0c\x63ontributors\x18\x04 \x03(\t\x12\x0e\n\x06weight\x18\x05 \x01(\x03\"5\n\rDistributions\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x14\n\x0c\x64istribution\x18\x02 \x01(\x0c\"\x81\x01\n\x0fScaffoldWeights\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\r\n\x05round\x18\x02 \x01(\x05\x12\x0f\n\x07weights\x18\x03 \x01(\x0c\x12\x14\n\x0c\x63ontributors\x18\x04 \x03(\t\x12\x0e\n\x06weight\x18\x05 \x01(\x03\x12\x18\n\x10\x63ontrol_variates\x18\x06 \x01(\x0c\" \n\x10HandShakeRequest\x12\x0c\n\x04\x61\x64\x64r\x18\x01 \x01(\t\"/\n\x0fResponseMessage\x12\x12\n\x05\x65rror\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_error2\xf5\x02\n\x0cNodeServices\x12:\n\thandshake\x12\x16.node.HandShakeRequest\x1a\x15.node.ResponseMessage\x12<\n\ndisconnect\x12\x16.node.HandShakeRequest\x1a\x16.google.protobuf.Empty\x12\x34\n\x0csend_message\x12\r.node.Message\x1a\x15.node.ResponseMessage\x12\x31\n\tadd_model\x12\r.node.Weights\x1a\x15.node.ResponseMessage\x12>\n\x10\x61\x64\x64_distribution\x12\x13.node.Distributions\x1a\x15.node.ResponseMessage\x12\x42\n\x12\x61\x64\x64_model_scaffold\x12\x15.node.ScaffoldWeights\x1a\x15.node.ResponseMessageb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='node.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='node.Message.source', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ttl', full_name='node.Message.ttl', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hash', full_name='node.Message.hash', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cmd', full_name='node.Message.cmd', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='args', full_name='node.Message.args', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='round', full_name='node.Message.round', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_round', full_name='node.Message._round',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=49,
  serialized_end=158,
)


_WEIGHTS = _descriptor.Descriptor(
  name='Weights',
  full_name='node.Weights',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='node.Weights.source', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='round', full_name='node.Weights.round', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weights', full_name='node.Weights.weights', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contributors', full_name='node.Weights.contributors', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weight', full_name='node.Weights.weight', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=255,
)


_DISTRIBUTIONS = _descriptor.Descriptor(
  name='Distributions',
  full_name='node.Distributions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='node.Distributions.source', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='distribution', full_name='node.Distributions.distribution', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=310,
)


_SCAFFOLDWEIGHTS = _descriptor.Descriptor(
  name='ScaffoldWeights',
  full_name='node.ScaffoldWeights',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='node.ScaffoldWeights.source', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='round', full_name='node.ScaffoldWeights.round', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weights', full_name='node.ScaffoldWeights.weights', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contributors', full_name='node.ScaffoldWeights.contributors', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weight', full_name='node.ScaffoldWeights.weight', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='control_variates', full_name='node.ScaffoldWeights.control_variates', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=442,
)


_HANDSHAKEREQUEST = _descriptor.Descriptor(
  name='HandShakeRequest',
  full_name='node.HandShakeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='addr', full_name='node.HandShakeRequest.addr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=444,
  serialized_end=476,
)


_RESPONSEMESSAGE = _descriptor.Descriptor(
  name='ResponseMessage',
  full_name='node.ResponseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='node.ResponseMessage.error', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_error', full_name='node.ResponseMessage._error',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=478,
  serialized_end=525,
)

_MESSAGE.oneofs_by_name['_round'].fields.append(
  _MESSAGE.fields_by_name['round'])
_MESSAGE.fields_by_name['round'].containing_oneof = _MESSAGE.oneofs_by_name['_round']
_RESPONSEMESSAGE.oneofs_by_name['_error'].fields.append(
  _RESPONSEMESSAGE.fields_by_name['error'])
_RESPONSEMESSAGE.fields_by_name['error'].containing_oneof = _RESPONSEMESSAGE.oneofs_by_name['_error']
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['Weights'] = _WEIGHTS
DESCRIPTOR.message_types_by_name['Distributions'] = _DISTRIBUTIONS
DESCRIPTOR.message_types_by_name['ScaffoldWeights'] = _SCAFFOLDWEIGHTS
DESCRIPTOR.message_types_by_name['HandShakeRequest'] = _HANDSHAKEREQUEST
DESCRIPTOR.message_types_by_name['ResponseMessage'] = _RESPONSEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:node.Message)
  })
_sym_db.RegisterMessage(Message)

Weights = _reflection.GeneratedProtocolMessageType('Weights', (_message.Message,), {
  'DESCRIPTOR' : _WEIGHTS,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:node.Weights)
  })
_sym_db.RegisterMessage(Weights)

Distributions = _reflection.GeneratedProtocolMessageType('Distributions', (_message.Message,), {
  'DESCRIPTOR' : _DISTRIBUTIONS,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:node.Distributions)
  })
_sym_db.RegisterMessage(Distributions)

ScaffoldWeights = _reflection.GeneratedProtocolMessageType('ScaffoldWeights', (_message.Message,), {
  'DESCRIPTOR' : _SCAFFOLDWEIGHTS,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:node.ScaffoldWeights)
  })
_sym_db.RegisterMessage(ScaffoldWeights)

HandShakeRequest = _reflection.GeneratedProtocolMessageType('HandShakeRequest', (_message.Message,), {
  'DESCRIPTOR' : _HANDSHAKEREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:node.HandShakeRequest)
  })
_sym_db.RegisterMessage(HandShakeRequest)

ResponseMessage = _reflection.GeneratedProtocolMessageType('ResponseMessage', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEMESSAGE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:node.ResponseMessage)
  })
_sym_db.RegisterMessage(ResponseMessage)



_NODESERVICES = _descriptor.ServiceDescriptor(
  name='NodeServices',
  full_name='node.NodeServices',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=528,
  serialized_end=901,
  methods=[
  _descriptor.MethodDescriptor(
    name='handshake',
    full_name='node.NodeServices.handshake',
    index=0,
    containing_service=None,
    input_type=_HANDSHAKEREQUEST,
    output_type=_RESPONSEMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='disconnect',
    full_name='node.NodeServices.disconnect',
    index=1,
    containing_service=None,
    input_type=_HANDSHAKEREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='send_message',
    full_name='node.NodeServices.send_message',
    index=2,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_RESPONSEMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='add_model',
    full_name='node.NodeServices.add_model',
    index=3,
    containing_service=None,
    input_type=_WEIGHTS,
    output_type=_RESPONSEMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='add_distribution',
    full_name='node.NodeServices.add_distribution',
    index=4,
    containing_service=None,
    input_type=_DISTRIBUTIONS,
    output_type=_RESPONSEMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='add_model_scaffold',
    full_name='node.NodeServices.add_model_scaffold',
    index=5,
    containing_service=None,
    input_type=_SCAFFOLDWEIGHTS,
    output_type=_RESPONSEMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NODESERVICES)

DESCRIPTOR.services_by_name['NodeServices'] = _NODESERVICES

# @@protoc_insertion_point(module_scope)
